### ISSUE TITLE
Version 1.1.0b Displays Stock Reputation Bar Instead Of RP-1 Numbers

### ISSUE THREAD

**Issue by Razgriz1** [zapSNH/ZTheme#8]
Using v1.1.0b alongside RP-1 shows the stock reputation bar instead of RP-1's number readout.
![image](https://github.com/zapSNH/ZTheme/assets/13578855/c54cb7d2-cfdf-435c-a546-b13e37ed5c64)

**Comment by zapSNH** [comment]
Should be fixed in v1.1.1. Please verify.

**Comment by Razgriz1** [comment]
That does not appear to help. I also tried upping the priority of the RP-1 HUD replacement, but it looks like somehow the stock HUD replacement is still overwriting it. The confidence meter gets the correct replacement (`RP-1/confidence_background`) but the reputation meter is still showing as `UIElements_14`, instead of `rep_background`. I also tried making a copy of `rep_background` in the RP-1 folder and naming it `UIElements_14` as well, and while this did give the correct UI element, it did not display the numbers. Perhaps RP-1 is doing its reputation UI element work after HUD replacer does its thing?

**Comment by zapSNH** [comment]
Can you try deleting `UIElements_14`?

**Comment by Razgriz1** [comment]
Deleting `UIElements_14` just reverts to the stock version of the same texture.

And no, I cannot see the reputation. Neither normally, nor when deleting the aforementioned texure. It looks like there may be an additional opaque layer (perhaps `UIElements_13`?) that is also present and might cover up the text

**Comment by zapSNH** [comment]
I don't really know what's causing this. `UIElements_13` didn't recieve any changes since v0.9.7.1 and it worked before.
How about reverting to HUDReplacer `v1.2.10-beta`? That's the version I tested where the rep bar showed up properly.

**Comment by Razgriz1** [comment]
Hmmm, neither of those worked. Perhaps it's an issue on my end. I'll try a completely new RP-1 install in the morning to see if I can replicate.

**Comment by kemot221** [comment]
Just wanted to add that I'm also encountering this issue on version 1.1.1. I have not made any changes to the config, or the files, but I can confirm the problem does not occur when ZTheme is uninstalled.

**Comment by zapSNH** [comment]
bah. Can you revert to ZTheme `v1.0.0` but keep HUDReplacer on `v1.2.11-beta` to see if it works there?

**Comment by kemot221** [comment]
`v1.0.0` loads the non-ZTheme RP-1 textures for both confidence and reputation. `v1.1.0` `v1.1.0b` and `v1.1.1` all show `UiElements_14`.

**Comment by zapSNH** [comment]
If `v1.0.0` works with RP-1 then I guess use that for the time being while the issue is being investigated.

**Comment by kemot221** [comment]
I've went into paint and changed the dimensions of ZTheme `rep_background` to 204x52 from 203x51. It loaded correctly on `v1.1.0`, didn't test on other versions yet, but I'm guessing it'll work.

**Comment by zapSNH** [comment]
Probably my last comment for the night but can you resize `rep_background` to 204x51 and see if that works? That's the size of [`rep_background` in RP-1's source.](https://github.com/KSP-RO/RP-1/blob/3121cdcfde005a0500ad9b2a332811eef0c8cf42/Assets/rep_background.png)

**Comment by kemot221** [comment]
Yes, it's working with 203x52

**Comment by zapSNH** [comment]
> I've went into paint and changed the dimensions of ZTheme `rep_background` to 204x52 from 203x51. It loaded correctly on `v1.1.0`, didn't test on other versions yet, but I'm guessing it'll work.
 
Is it actually 204x52 for you? Both Firefox and GNOME's image viewer say that it's 203x51.
![image](https://github.com/zapSNH/ZTheme/assets/134786889/a9a1da05-0558-4528-8e64-14f392204636)

**Comment by zapSNH** [comment]
oh wait im stupid

**Comment by zapSNH** [comment]
I've published a new release. Can ya'll see if it fixes it?
https://github.com/zapSNH/ZTheme/releases/tag/v1.1.2

**Comment by kemot221** [comment]
Yup, it works on this release
